###

GET http://localhost:8080/api/cateringorder
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/cateringorder/1
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/cateringorder/43/19
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "orderid": 1,
  "cateringid": 1,
  "datecateringoptions": "2019-01-10T13:37:42",
  "datecateringdefinite": "2019-01-10T13:37:42",
  "datecateringsend": "2019-01-10T13:37:42",
  "contactcateringoption": "opties enzo",
  "contactcateringdefinite": "wat moet hier",
  "contactcateringsend": "ja",
  "note": "jajajaja"
}

###

PUT http://localhost:8080/api/cateringorder/4
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "datecateringoptions": "2019-01-10T13:37:42",
  "datecateringdefinite": "2019-01-10T13:37:42",
  "datecateringsend": "2019-01-10T13:37:42",
  "contactcateringoption": "opties enzo",
  "contactcateringdefinite": "wat moet hier",
  "contactcateringsend": "ja",
  "note": "jajajaja"
}

###

DELETE http://localhost:8080/api/cateringorder/6
Accept: application/json
Authorization: Basic Arthur abc

###