###

GET http://localhost:8080/api/caterings
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/caterings/18
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/caterings/6
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "cateringName" : "AH",
  "contactPerson" : "Joost",
  "zipcode" : "1234KL",
  "address" : "teststraat 50",
  "city" : "Den Haag",
  "phone" : "0123456789",
  "cateringPrice" : 130.50,
  "note" : null
}

###

PUT http://localhost:8080/api/caterings/19
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "cateringName": "Scandinavian Airlines",
  "contactPerson": "Jeroen",
  "zipcode": "1234KL",
  "address": "teststraat 50",
  "city": "Eindoven",
  "phone": "0123456789",
  "cateringPrice": 130.50,
  "note": null
}

###

POST http://localhost:8080/api/cateringimages/19
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
"image" : "image/sas.jpg"
}

###
DELETE http://localhost:8080/api/cateringimages/3
Accept: application/json
Authorization: Basic Arthur abc

###
DELETE http://localhost:8080/api/caterings/18
Accept: application/json
Authorization: Basic Arthur abc

###