###

GET http://localhost:8080/api/customers
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/customers/4
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/customers
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "title": "mevrouw",
  "first_name": "Nina",
  "infix": "van der",
  "last_name": "Hulde",
  "address": "Bloemenlaan 57",
  "zipcode": "9284WL",
  "country": "Nederland",
  "city": "Nijmegen",
  "gender": "v",
  "email_addresses": [
    { "email": "test@test.com" }
  ],
  "phone_numbers": [
    { "phonenumber": "06-43430303" }
  ]
}

###

PUT http://localhost:8080/api/customers/4
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "title": "heer",
  "first_name": "Niels",
  "infix": "der",
  "last_name": "achternaam",
  "address": "Straat 123",
  "zipcode": "2323JA",
  "country": "Nederland",
  "city": "Alkmaar",
  "gender": "m",
  "email_addresses": [
    { "email": "test12@test.com" }
  ],
  "phone_numbers": [
    { "phonenumber": "06-43430309" }
  ]
}

###

DELETE http://localhost:8080/api/customers/3
Accept: application/json
Authorization: Basic Arthur abc

###