###

GET http://localhost:8080/api/emailtexts
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/emailtexts/2
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/emailtexts
Content-Type: application/json
Accept: application/json
Authorization: basic Arthur abc

{
  "emailType": "Offerte goedgekeurd",
  "emailText": "Geachte <klant>, \nUw factuur is zojuist aangemaakt.\nMet vriendelijke groeten Arthur Bol"
}

###

PUT http://localhost:8080/api/emailtexts/4
Content-Type: application/json
Accept: application/json
Authorization: basic Arthur abc

{
  "emailType": "Aanmaning betalingsachterstand",
  "emailText": "Geachte <klant>, \nHierbij moeten we u mededelen dat u nog een openstaande rekening hebt die betaald moet worden. U kunt kiezen om per termijn te betalen of direct in een keer. \nMet vriendelijke groeten Arthur Bol"
}

###

DELETE http://localhost:8080/api/emailtexts/1
Accept: application/json
Authorization: basic Arthur abc

###