
###

GET http://localhost:8080/api/events
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/events/52
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/events/1/39
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "ownEvent": true,
  "name": "Expeditie Hello World",
  "description": "This is a great event",
  "program": "Fietstocht",
  "duration": "1:30",
  "options": null,
  "pricePerPerson": 130.5,
  "priceBuyPerPerson": 0,
  "btw": 0.21,
  "note": null
}

###
POST http://localhost:8080/api/eventimage/1
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "imagePath": "image/expeditiehelloworld.jpg"
}

###

DELETE http://localhost:8080/api/events/49
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/eventlocation
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "name" : "Delft",
  "description" : "It is a nice place",
  "routePicture" : "image/denhaag.jpg"
}

###
