###

GET http://localhost:8080/api/orders
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/orders/2
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/orders
Content-Type: application/json
Accept: application/json
Authorization: Basic Liselot abc

{
  "customerid": 7,
  "dateorder": "2019-01-10T13:37:42",
  "dateevent": "2019-01-10T13:37:42",
  "note": "test note",
  "starttime": "2019-01-10T13:37:42",
  "endtime": "2019-01-10T13:37:42",
  "eventid": 2,
  "quotations": [
    {
      "datequotation": "2019-01-10T13:37:42",
      "bankaccount": "ABNA4200982",
      "pricebtw": 1212,
      "pricepp": 40
    }
  ],
  "invoices": [
    {
      "dateinvoice": "2019-01-10T13:37:42",
      "paymentextras": "dit kost te veel",
      "pricepp": 1242.99,
      "pricebtw": 12453,
      "othercosts": 120,
      "othercostsbtw": 190,
      "tobepaid": 1242,
      "paid": 4,
      "datepartpaid": "2019-01-10T13:37:42",
      "datefullpaid": "2019-01-10T13:37:42",
      "bankaccount": "INGB13371337",
      "dateinvoicemailsend": "2019-01-10T13:37:42",
      "excludefrominvoicealert": true
    }
  ]
}

###

PUT http://localhost:8080/api/orders/43
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "orderid": 43,
  "dateorder": "2019-01-10T13:37:42",
  "dateinvoice": "2019-01-10T13:37:42",
  "paymentextras": "dit kost veel te veel",
  "pricepp": 1542.99,
  "pricebtw": 12453,
  "othercosts": 420,
  "othercostsbtw": 190,
  "tobepaid": 1242,
  "paid": 4,
  "datepartpaid": "2019-01-10T13:37:42",
  "datefullpaid": "2019-01-10T13:37:42",
  "bankaccount": "INGB13371337",
  "dateinvoicemailsend": "2019-01-10T13:37:42",
  "excludefrominvoicealert": true
}

###

DELETE http://localhost:8080/api/orders/1
Accept: application/json
Authorization: Basic Arthur abc

###