###

GET http://localhost:8080/api/suppliers
Accept: application/json

###

GET http://localhost:8080/api/suppliers/1
Accept: application/json

###

POST http://localhost:8080/api/suppliers
Content-Type: application/json
Accept: application/json
Authorization: Basic Liselot abc

{
  "name": "Hoboken",
  "contact_person": "Hoboken45",
  "supervisor": "Hoboken45",
  "website" : "hoboken.nl",
  "note" : null,
  "image" : "image/hoboken.jpg",
  "email_addresses": [
    { "email": "sushi45@example.com" }
  ],
  "phone_numbers": [
    { "phone": "+31 6 12345666" }
  ],
  "contracts": [
    {
      "type": true,
      "title": "Inkoop",
      "description": "Sushi rolls verkoop contract",
      "inclubtw": "Sushi rolls | 20-;",
      "percentage": 21,
      "pre_conditions": "Minimaal 500 sushi rolls afnemen",
      "insurance": "Geen",
      "responsibility": "Artemis",
      "extras": "5 sushi rolls gratis bij een afname van 1000 sushi rolls"
    }
  ],
  "addresses" : [
    {
      "address" : "Teststraat 138",
      "city" : "Delft",
      "zipcode" : "1234KL"
    }
  ]
}

###

DELETE http://localhost:8080/api/suppliers/5
Accept: application/json

###