###


GET http://localhost:8080/api/users
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/users/1
Accept: application/json
Authorization: Basic Arthur abc

###

POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json
Authorization: Basic Liselot abc

{
  "username": "johndoe",
  "password": "password"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
"username": "Danny",
"password": "password"
}

###
POST http://localhost:8080/api/instructors/
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "user_id": 2,
  "firstName": "Jan",
  "infix": "",
  "lastName": "Peter",
  "phoneNumber" : "0631254878",
  "email": "janpeter@beeventgroup.nl"
}
###

PUT http://localhost:8080/api/users/1
Content-Type: application/json
Accept: application/json

{
  "password": "newpassword"
}

###

DELETE http://localhost:8080/api/users/1
Accept: application/json

###
POST http://localhost:8080/api/employees/
Content-Type: application/json
Accept: application/json
Authorization: Basic Arthur abc

{
  "user_id": 3,
  "first_name": "Danny",
  "infix": "van",
  "last_name": "Tol",
  "email_addresses": [
    {
      "email": "dannyvantol@hotmail.com"
    },
    {
      "email": "dannyvantol@gmail.com"
    }
  ],
  "phone_numbers": [
    {
      "phone": "0631919685"
    }
  ]
}

###

GET http://localhost:8080/api/instructors/1
Accept: application/json
Authorization: Basic Arthur abc

###

GET http://localhost:8080/api/employees
Accept: application/json
Authorization: Basic Arthur abc

###